"""empty message

Revision ID: 26e44b608598
Revises: 46dc5054b42
Create Date: 2016-05-10 15:55:18.343730

"""

# revision identifiers, used by Alembic.
revision = '26e44b608598'
down_revision = '46dc5054b42'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.Column('project_address', sa.String(), nullable=True),
    sa.Column('project_manager_id', sa.Integer(), nullable=True),
    sa.Column('project_status', sa.String(length=10), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('property_owner', sa.String(), nullable=True),
    sa.Column('authority_having_jurisdiction_or_bldg_dept', sa.Text(), nullable=True),
    sa.Column('civicsolar_account_manager_id', sa.Integer(), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=False),
    sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.ForeignKeyConstraint(['civicsolar_account_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['project_form_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_form_fields')
    op.drop_table('project_form_sections')
    op.drop_table('projects')
    op.drop_table('contractors')
    ### end Alembic commands ###
